"""empty message

Revision ID: 0949fbaf306d
Revises: 66afcad5dccc
Create Date: 2018-12-25 23:56:53.314561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0949fbaf306d'
down_revision = '66afcad5dccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('img', sa.String(length=720), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'img')
    # ### end Alembic commands ###
